const Map<String, String> hdStrings = {
  'Saara data delete karo?': 'सारा डेटा डिलीट करें?',
  'Block list, history aur API key sab hat jayenge.': 'ब्लॉक लिस्ट, हिस्ट्री और API key सब हट जाएँगी।',
  'Saara data delete karo': 'सारा डेटा डिलीट करें',
  'Yes': 'हाँ',
  'No': 'नहीं',
  'Cancel': 'रद्द करें',
  'Number daalo': 'नंबर डालें',
  'Call karo': 'कॉल करें',
  'Aaj blocked': 'आज ब्लॉक हुए',
  'Spam alerts': 'स्पैम अलर्ट',
  'Recent calls': 'हाल की कॉल',
  'Recent calls dekhne ke liye call log ki permission do.': 'हाल की कॉल देखने के लिए कॉल लॉग की अनुमति दें।',
  'Permission do': 'अनुमति दें',
  'Koi call nahi mili': 'कोई कॉल नहीं मिली',
  'abhi': 'अभी',
  'Call history se delete karein?': 'कॉल हिस्ट्री से डिलीट करें?',
  'Permission allow karke dobara try karo': 'अनुमति देकर दोबारा कोशिश करें',
  'Contacts': 'कॉन्टैक्ट्स',
  'Recent calls dekhne ke liye call log ki permission chahiye. Ye data sirf aapke phone me rehta hai.': 'हाल की कॉल देखने के लिए कॉल लॉग की अनुमति चाहिए। यह डेटा सिर्फ़ आपके फ़ोन में रहता है।',
  'Permission nahi mili. Phone Settings > Apps > Call Guard > Permissions > Call logs me Allow karo, phir yahan wapas aao.': 'अनुमति नहीं मिली। फ़ोन Settings > Apps > Call Guard > Permissions > Call logs में Allow करें, फिर यहाँ वापस आएँ।',
  'Contacts dekhne ke liye Contacts ki permission chahiye. Ye data sirf aapke phone me rehta hai.': 'कॉन्टैक्ट्स देखने के लिए Contacts की अनुमति चाहिए। यह डेटा सिर्फ़ आपके फ़ोन में रहता है।',
  'Permission nahi mili. Phone Settings > Apps > Call Guard > Permissions > Contacts me Allow karo, phir yahan wapas aao.': 'अनुमति नहीं मिली। फ़ोन Settings > Apps > Call Guard > Permissions > Contacts में Allow करें, फिर यहाँ वापस आएँ।',
  'Koi recent call nahi mili': 'कोई हाल की कॉल नहीं मिली',
  'Koi contact nahi mila': 'कोई कॉन्टैक्ट नहीं मिला',
  'Blocked': 'ब्लॉक है',
  'Unknown': 'अज्ञात',
  'Shak: telemarketing / promotional number': 'शक: टेलीमार्केटिंग / प्रमोशनल नंबर',
  'Koi spam report nahi mili': 'कोई स्पैम रिपोर्ट नहीं मिली',
  'Category chuno:': 'श्रेणी चुनें:',
  'Block list me daalo': 'ब्लॉक लिस्ट में डालें',
  'Block hatao': 'ब्लॉक हटाएँ',
  'AI se poochho': 'AI से पूछें',
  'Poora 10 digit number daalo': 'पूरा 10 अंकों का नंबर डालें',
  'International number, savdhan rahein': 'अंतरराष्ट्रीय नंबर, सावधान रहें',
  'Shak: sabhi digit ek jaise hain': 'शक: सभी अंक एक जैसे हैं',
  'Number check karo': 'नंबर जाँचें',
  'Number block karo': 'नंबर ब्लॉक करें',
  'Block': 'ब्लॉक',
  'Hatane ke liye side me swipe karo': 'हटाने के लिए साइड में स्वाइप करें',
  'Koi number nahi mila': 'कोई नंबर नहीं मिला',
  'Settings': 'सेटिंग्स',
  'Call Guard default Phone app hai': 'Call Guard डिफ़ॉल्ट फ़ोन ऐप है',
  'Call Guard default Phone app nahi hai': 'Call Guard डिफ़ॉल्ट फ़ोन ऐप नहीं है',
  'Naam bolna, flip to silence aur Call Guard ki call screen tabhi chalti hain jab ye default ho.': 'नाम बोलना, flip to silence और Call Guard की कॉल स्क्रीन तभी चलती हैं जब यह डिफ़ॉल्ट हो।',
  'Default Phone app banao': 'डिफ़ॉल्ट फ़ोन ऐप बनाएँ',
  'Call blocking': 'कॉल ब्लॉकिंग',
  'Auto call blocking': 'ऑटो कॉल ब्लॉकिंग',
  'Block list wale numbers ki call apne aap reject': 'ब्लॉक लिस्ट वाले नंबरों की कॉल अपने आप रिजेक्ट',
  'Telemarketing numbers block karo': 'टेलीमार्केटिंग नंबर ब्लॉक करें',
  '140 aur 160 se shuru hone wale numbers. Kuch bank bhi 160 se call karte hain': '140 और 160 से शुरू होने वाले नंबर। कुछ बैंक भी 160 से कॉल करते हैं',
  'Chhupe hue number block karo': 'छिपे हुए नंबर ब्लॉक करें',
  'Jinka number dikhta nahi (hidden / private)': 'जिनका नंबर दिखता नहीं (hidden / private)',
  'Videsh ke numbers block karo': 'विदेशी नंबर ब्लॉक करें',
  '+91 ke alawa kisi bhi desh ka number': '+91 के अलावा किसी भी देश का नंबर',
  'Block hui call ka notification': 'ब्लॉक हुई कॉल की नोटिफ़िकेशन',
  'Call reject hone par notification': 'कॉल रिजेक्ट होने पर नोटिफ़िकेशन',
  'Awaaz aur ring': 'आवाज़ और रिंग',
  'Naam bolna': 'नाम बोलना',
  'Call aane par naam ya Unknown number bolna': 'कॉल आने पर नाम या Unknown number बोलना',
  'Spam caller awaaz': 'स्पैम कॉलर आवाज़',
  '140 ya 160 wale numbers par Spam caller bolna': '140 या 160 वाले नंबरों पर Spam caller बोलना',
  'Flip to silence': 'Flip to silence',
  'Ring ke dauran phone ulta karne par ringtone band': 'रिंग के दौरान फ़ोन उलटा करने पर रिंगटोन बंद',
  'Unknown number ka state (online AI)': 'अज्ञात नंबर का राज्य (online AI)',
  'Gemini API key se. Number Google ko jata hai': 'Gemini API key से। नंबर Google को जाता है',
  'Notification': 'नोटिफ़िकेशन',
  'Unknown caller ka chhota popup': 'अज्ञात कॉलर का छोटा पॉपअप',
  'Call aane par Call Guard ka notification': 'कॉल आने पर Call Guard की नोटिफ़िकेशन',
  'Daali nahi gayi': 'डाली नहीं गई',
  'Save': 'सेव करें',
  'About': 'जानकारी',
  'Privacy': 'गोपनीयता',
  'Block list aur history sirf aapke phone me rehti hai. AI se poochho ya state wale switch par number Google Gemini ko jata hai.': 'ब्लॉक लिस्ट और हिस्ट्री सिर्फ़ आपके फ़ोन में रहती है। AI से पूछने या state वाले स्विच पर नंबर Google Gemini को जाता है।',
  'Language / Bhasha': 'भाषा',
};
